### ISSUE TITLE
Using ncurses with golang binding "goncurses" package

### ISSUE THREAD

**Issue by TinSoldier6** [Homebrew/homebrew-dupes#396]
I was having a problem getting ncurses to work with Google's Go language binding "goncurses" package.

I had two issues: 1) goncurses couldn't find ncurses.pc in the pkg-config path and 2) curses.h couldn't find `<ncursesw/ncurses_dll.h>` in the include path.

I solved problem 1 by linking ncurses.pc, ncursesw.pc, and the other .pc files in /usr/local/lib/pkgconfig to the ncursesw.pc files in `{lib}/pkgconfig`. If I knew how to do this in Ruby then I would suggest doing it in the formula under make_libcurses_symlinks or under its own function.

Problem 2 is because I think the ncurses package expects all of its header files to be in the default include path -- curses.h and others include `<ncursesw/ncurses_dll.h>`. The .pc file adds `{include}/ncursesw` to the compiler include path but not its parent directory. I edited the .pc files to include the parent directory. I don't know if this is the right solution, but it seemed more reasonable than editing curses.h.

I changed the line in ncursesw.pc as follows:
Old: `Cflags: -I${includedir}`
New: `Cflags: -I${includedir} -I${includedir}/..`

There's probably a better solution, but this is what worked for me. The Go language examples seem to work correctly.

**Comment by cswank** [comment]
If os x already provides nurses, where is it?  I can find no reference to it anywhere (google included).

**Comment by mistydemeo** [comment]
ncurses is located at `/usr/lib/libncurses.dylib`, and its headers are in `/usr/include` (or the equivalent SDK paths). Note that, despite the library name, this is `ncursesw` and includes the wide functions.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
