### ISSUE TITLE
OpenSSH with keychain support may expose key passphrase

### ISSUE THREAD

**Issue by nbrownus** [Homebrew/homebrew-dupes#413]
It's a bit convoluted but I noticed this after struggling and finally succeeding to get `sshd` running on Yosemite.

Steps to reproduce (only tested with private keys that have a passphrase)

- Install `openssh` with `--with-keychain-support`
- Stop apples `sshd`
- Start brew's `sshd`, however you want
- Log into your local machine `ssh localhost`
- In the same terminal, attempt to log into any other host, localhost works here as well `ssh localhost`
- Notice that no matter how hard you try to type in the password prompt your text always appears in the terminal

**Comment by chdiza** [comment]
Is this the issue that MacPorts attempts to fix with the "pam" patch?

https://trac.macports.org/browser/trunk/dports/net/openssh/Portfile?rev=131258

**Comment by DomT4** [comment]
We won't be [supporting the keychain](https://github.com/Homebrew/homebrew-dupes/pull/482#issuecomment-118994372) patch going forwards.
