### ISSUE TITLE
cntlm failed to build on OS 10.6.8

### ISSUE THREAD

**Issue by giskard22** [Homebrew/homebrew-dupes#414]
On OS 10.6.8 with last available Xcode (4.2), cntlm fails to build. This error appears multiple times:

    cc1: error: unrecognized command line option "-Wno-unused-but-set-variable"

See https://gist.github.com/d93de192bdaa332ac7a3 for full output.

Quick uninformed research seems to indicate this option requires a newer version of GCC than you get with Xcode 4.2. I'm not sure this is actually a homebrew issue because you get the same error if you manually download and compile. If this is more properly reported to the cntlm project, please let me know.

**Comment by jacknagel** [comment]
cntlm is in the primary repository, so please report this to https://github.com/Homebrew/homebrew, thanks.

**Comment by giskard22** [comment]
Oh duh, sorry (was thinking of rsync for some reason).
