### ISSUE TITLE
OpenSSH caveats instructions for starting ssh-agent on bash login. Is this the best way?

### ISSUE THREAD

**Issue by olbrew** [Homebrew/homebrew-dupes#418]
After the installation of the OpenSSH package it is advises to add the following to your bash_profile:

    eval $(ssh-agent)

    function cleanup {
        echo "Killing SSH-Agent"
        kill -9 $SSH_AGENT_PID
    }
    trap cleanup EXIT

Could somebody explain to me why this is needed?
With it every time you open a new window/tab/split-screen/... a new instance of bash/zsh/... starts and it will start an ssh-agent for every one of those.
Wouldn't it be better to just let the ssh-agent start whenever the first ssh command is entered and keep it running till the end of the session (when user logs out or shuts down), since this is used with the OS X keychain which also stays unlocked until the end of the session? This is the standard behaviour without the above code and that way you have only one ssh-agent running at all times, which seems simpler.

**Comment by DomT4** [comment]
We won't be [supporting the keychain](https://github.com/Homebrew/homebrew-dupes/pull/482#issuecomment-118994372) patch going forwards.
