### ISSUE TITLE
Drop openssh

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/homebrew-dupes#428]
The openssh formula contains a lot of questionable stuff that I'm uncomfortable maintaining. Rather than strip it down and ship something that isn't useful to people, I suggest we remove it and let the community maintain it elsewhere.

/cc @mistydemeo

**Comment by jacknagel** [comment]
See #413 and #418, I don't want to be responsible for this stuff.

**Comment by chdiza** [comment]
It seems to me that the problems all stem from that keychain patch.  I'd rather keep the formula but ditch the patch entirely; let those who really need it roll their own.

Maybe the launchd patch is behind some of this too, in which case, we should just dump it and let those who need it roll their own.

Not all openssh users need those "fancy" things.

**Comment by mistydemeo** [comment]
@jacknagel I'm with you on this - I would rather not continue to maintain these patches. I wouldn't mind maintaining a more vanilla formula, but I do wonder if it's something users would find useful, given the frustration expressed in the past when these patches were dropped.

**Comment by jacknagel** [comment]
>I'd rather keep the formula but ditch the patch entirely; let those who really need it roll their own.

In my experience, people will just keeping submitting issues and PRs re-adding the things that were removed. I'd like to try and avoid that administrative overhead. On the other hand, people may just re-submit an entire openssh formula, so I don't know if it will help.

**Comment by chdiza** [comment]
Perhaps the formula could contain a "please do not try to add such and such" comment, sort of like in the `vim` formula (line 73) where users are begged not to make PR that hardcodes a ruby path.  Or like how there probably should be such a comment in `mutt.rb` telling people to stop asking for the sidebar patch.

**Comment by h0lzi** [comment]
It would be nice to have openssh still around (Because the apple Provided one is broken).
I don't care about the keychain patch and would drop that.

**Comment by olbrew** [comment]
@h0lzi could you elaborate on what's wrong exactly with Apple's provided one?
After having too much problems with the Homebrew version I'm thinking of returning to the Apple one, sure it will not update as fast, but recently it seems like they have done more regular updates of their command line tools package.

**Comment by jquagga** [comment]
Well, as someone who is guilty of preparing to open an issue to add more features to this (add the HPN patch back), I think that even having the "vanilla" stripped down OpenSSH is useful.  The Apple included version of the ssh client is rather old; it's nice to have something newer and to have a base formula I can add patches to if I desire.

**Comment by h0lzi** [comment]
@olbrew well the openssh Version from apple is quite old 6.2 and build only against the old openssl 0.9.8 that apple still ships which prevents newer ciphers to be used e.g. aes256-gcm@openssh.com,aes128-gcm@openssh.com

**Comment by jbergstroem** [comment]
Ciphers is for me the sole reason I'm using the homebrew-dupes version. There's unfortunately not many options if you don't want to setup a jump host.

**Comment by DomT4** [comment]
We won't be [supporting the keychain](https://github.com/Homebrew/homebrew-dupes/pull/482#issuecomment-118994372) patch going forwards. We'll continue to support a more "vanilla" OpenSSH.
