### ISSUE TITLE
whois client does not have idn support

### ISSUE THREAD

**Issue by aalmenar** [Homebrew/homebrew-dupes#447]
OSX default whois client does not have IDN support, so i installed homebrew one for it, but found it has the same shortcomming.

On any new linux distro (Debian 7, Manajaro, Arch) making a whois for a domain like 猪肉.com, request gets converted to xn--y7x48z.com, but in OSX and homebrew one, the coding is sent as it is.

The difference it's that the linux distros one, has been compiled with libidn support. Since whois protocol on servers only accepts ascii (As per RFC 3912), this library should be mandatory on its use.

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!

**Comment by jacknagel** [comment]
Would accept a pull request.
