### ISSUE TITLE
Some notes on ncurses.rb

### ISSUE THREAD

**Issue by larryhynes** [Homebrew/homebrew-dupes#455]
The caveats for `brew install ncurses` gives the following build variables:

```
LDFLAGS:  -L/usr/local/opt/ncurses/lib
CPPFLAGS: -I/usr/local/opt/ncurses/include
```

These don't appear to work for ncurses wide support - which seems to be a compelling reason to install ncurses from homebrew - or at least the following worked more reliably for me this evening when installing [lumail](https://github.com/skx/lumail/):

```
LDFLAGS: -L/usr/local/opt/ncurses/lib -lncursesw
CPPFLAGS: -I/usr/local/opt/ncurses/include/ncursesw
```

These I divined using:

`pkg-config --libs /usr/local/opt/ncurses/lib/pkgconfig/ncursesw.pc` and
`pkg-config --cflags /usr/local/opt/ncurses/lib/pkgconfig/ncursesw.pc`

So with that out of the way, and the compiler knowing where to look, it threw a lot of errors along the lines of:

`/usr/local/Cellar/ncurses/5.9/include/ncursesw/cursesw.h:36:10: fatal error: 'ncursesw/etip.h' file not found`

It seems that all the `# include`s in the various files in `../include/ncursesw` are of the form `#  include   <ncursesw/curses.h>`. Changing those to `#  include   <curses.h>`, i.e. removing the leading `ncursesw/` means that all is nice and dandy and things compile.

I'm not sure how much of this is a product of my own dogged determination this evening to compile a particular program, how much is upstream-related and how much is under the control of Homebrew! :smile:

I mention it here only in case it is of relevance to Homebrew, I will probably also get in touch with the lumail developer and see if things can be better addressed there.

It is possible that the Homebrew caveats might bear closer inspection.

**Comment by DomT4** [comment]
Those caveats at the top there you're seeing there in particular are automatically generated for ` keg_only ` formulae - They aren't intended to be super-specific to a formulae.

**Comment by mistydemeo** [comment]
The pkg-config issue you're noticing is unfortunately one we're already aware of - #396. :( There appears to be a bug in the pkg-config files in recent versions of ncurses, which causes it to not provide one of the two `-I` flags it needs.

**Comment by larryhynes** [comment]
@DomT4 Indeed. They are not, however, very useful as they currently stand; I might even go as far as to suggest one might be better off without them in their current form. I am suggesting that it might be an improvement if they were a little more specific to this particular formula, in this particular instance.

@mistydemeo Thanks for your efforts – as always! — we shall wait and see what comes of it upstream.

**Comment by jacknagel** [comment]
The caveats are designed to show what additional action you need to take as a consequence of the formula being keg-only. That you also need to specify `-lncurses` is not one of these consequences, so it doesn't belong in the caveats.

The caveats are a stab at something generic and applicable across any library.

I understand the confusion, but I don't think we want to be in the business of writing explicit compilation instructions on a per-formula basis.
