### ISSUE TITLE
brew update - Deleted Formulae homebrew/dupes/tidy

### ISSUE THREAD

**Issue by louisl** [Homebrew/homebrew-dupes#461]
I did a brew update today and noticed `homebrew/dupes/tidy` was in the Deleted Formulae.

Is there a reason for this? I was previously using homebrew/dupes/tidy --HEAD for HTML5 linting.

**Comment by DomT4** [comment]
See #456 and https://github.com/Homebrew/homebrew/pull/39010.

**Comment by louisl** [comment]
Thanks,

OK so now we need to use tidy5 instead of tidy in the command line. I've done a quick fix for myself but this could be a breaker for various plugins and apps that reference just 'tidy' and are expecting to get the HTML 5 version if installed.

FYI, My main usage is with the html tidy linter for SublimeText https://github.com/SublimeLinter/SublimeLinter-html-tidy

**Comment by DomT4** [comment]
It's easy enough to add an optional symlink from `tidy5` to `tidy`. It probably couldn't be mandatory given OS X natively ships a `tidy` executable we'd be overriding by placing another `tidy` executable earlier in the `$PATH`, but the maintainers may not hate the idea if it's optional.

**Comment by louisl** [comment]
Maybe note it like on the php installers? In the install output text, similar to:-
```
If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
```

**Comment by Andergraw** [comment]
Anything on this?
I have been getting really crazy, because of my "newbieness"...
The point is: should I just rename the tidy5 symlink brew automatically creates? Shall this bring any problem?
Thanks.

**Comment by danielbayley** [comment]
You could put
```bash
export PATH=$(brew --prefix)/bin:$PATH
alias tidy=tidy5
```
in your `~/.bashrc` to solve this.

**Comment by jacknagel** [comment]
Would accept a PR to add an optional symlink to the tidy. But I'm not sure it's worth it since in the process of discovering the option, you'd realize what the problem is and just add a shell alias.

**Comment by ntwb** [comment]
Just to add similar to @louisl I use the same Sublime Text linter plugin, the latest version of this now supports `Tidy5` see https://github.com/SublimeLinter/SublimeLinter-html-tidy/releases/tag/1.0.15

**Comment by Andergraw** [comment]
Yeah, I was dealing with ST2...
Finally I surrendered to the evidence and installed ST3.
Thanks!
