### ISSUE TITLE
apple-gcc42 doesn't include dynamic libraries

### ISSUE THREAD

**Issue by dmwelch** [Homebrew/homebrew-dupes#464]
I have a binary that depends on libgfortran.3.dylib, which isn't provided by the recipe. I've found this source (http://hpc.sourceforge.net) which appears to work.

**Comment by mistydemeo** [comment]
The gfortran libraries they provide there are from newer GCC versions - 4.7 through 5. The `gcc` formula in the main repository installs libgfortran by default, and the versioned formulae in homebrew/versions optionally provide fortran support. Do those work for you?

**Comment by jacknagel** [comment]
Closing per the above.
