### ISSUE TITLE
Cannot use ed25519 or ssh-agent with homebrew's ssh

### ISSUE THREAD

**Issue by brianmhunt** [Homebrew/homebrew-dupes#469]
This is related to #242.

Using ed25519 with ssh-agent is *almost* possible on Mac OS X right now.

In particular, one can [set up homebrew's ssh](http://www.dctrwatson.com/2013/07/how-to-update-openssh-on-mac-os-x/) with:

```sh
$ homebrew brew tap homebrew/dupes
$ brew install openssh --with-brewed-openssl --with-keychain-support
$ launchctl stop org.openbsd.ssh-agent
$ launchctl unload -w /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
$ sudo vi /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
   - change /usr/bin/ssh-agent to /usr/local/bin/ssh-agent
$ launchctl load -w -S Aqua /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
```

One can then logout and log in/restart, or in each shell run `$ export SSH_AUTH_SOCK=$(launchctl getenv SSH_AUTH_SOCK)`.

In theory this should get one up and running. However you will note in ` /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist` the `<string>-l</string>` part that passes a `-l` option to `ssh-agent`. This is an undocumented argument honoured in the Apple version of `ssh-agent` but not on the homebrew version, and passing the argument causes the homebrew version to fail.

The problem is discussed [on gossamer-threads/openssh](http://www.gossamer-threads.com/lists/openssh/dev/52278), which highlights the portions inside `#ifdef __APPLE_LAUNCHD__ ` of [openssh/ssh-agent.c](http://opensource.apple.com/source/OpenSSH/OpenSSH-166/openssh/ssh-agent.c)

There are no apparent work-arounds that I have seen; it looks like homebrew's `ssh-agent` has to be patched to support Apple's `-l` option.

**Edit** It is probably worth linking #428, #413, and #418 since at least the latter two may be addressed if this issue is resolved.

**Comment by yveslaroche** [comment]
I can confirm that this is working for me as well.

```sh
sudo sed -i 's/\/usr\/bin\/ssh-agent/\/opt\/local\/bin\/ssh-agent/' /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
```
Then logout or do:
```sh
launchctl stop org.openbsd.ssh-agent
launchctl unload -w /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
launchctl load -w -S Aqua /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
export SSH_AUTH_SOCK=$(launchctl getenv SSH_AUTH_SOCK)
```

**Comment by DomT4** [comment]
We won't be [supporting the keychain](https://github.com/Homebrew/homebrew-dupes/pull/482#issuecomment-118994372) patch going forwards.

**Comment by brianmhunt** [comment]
Thats probably wise; thanks for the update, @DomT4 

Cheers
