### ISSUE TITLE
OpenSSH 6.8p1 sha256 mismatch

### ISSUE THREAD

**Issue by tomaszzielinski** [Homebrew/homebrew-dupes#480]
As per https://github.com/Homebrew/homebrew-dupes/blob/b07aaaf79870c0ba973c32c181b79238bd6f6831/openssh.rb sha256 of the source tarball should be 3ff64ce73ee1244... whereas for a freshly downloaded http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-6.8p1.tar.gz it's 409c69d0e2b03a581a688804b0388fdde4d828d8b525aec0389f637ab7e7247d.

**Comment by DomT4** [comment]
It's as expected here:

```
==> Fetching openssh from homebrew/homebrew-dupes
==> Downloading http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-6.8p1.tar.gz
######################################################################## 100.0%
Downloaded to: /usr/local/var/homebrew/cache/openssh-6.8p1.tar.gz
SHA1: cdbc51e46a902b30d263b05fdc71340920e91c92
SHA256: 3ff64ce73ee124480b5bf767b9830d7d3c03bbcb6abe716b78f0192c37ce160e
```

Could be a local network error, unless you have a `.curlrc` file. If you `tar -tzf` the tarball are the expected contents inside?

**Comment by tomaszzielinski** [comment]
OK, sorry for the false alarm. I didn't use curl, I downloaded openssh-6.8p1.tar.gz using Chrome and apparently something (Chrome?) unzips it before saving to disk.
