### ISSUE TITLE
gdb 7.9.1 broken under MacOS Yosemite 10.10.4

### ISSUE THREAD

**Issue by rbdavis** [Homebrew/homebrew-dupes#483]
Some recent gdb  (or gcc?) update has completely broken my debugging environment under MacOS Yosemite 10.10.4. (I typically use gdb under ddd.) When started, gdb can't find a bunch of stuff under /BinaryCache/..., which of course does not exist on my system:

> gdb D-mac_x8664/bsavg
GNU gdb (GDB) 7.9.1
...
(gdb) break main
Breakpoint 1 at 0x100001275: file bsavg.c, line 73.
(gdb) r
Starting program: /Users/hmrgsoft/prog/bsavg/D-mac_x8664/bsavg 
warning: `/BinaryCache/coreTLS/coreTLS-35.30.2~2/Objects/coretls.build/coretls.build/Objects-normal/x86_64/system_coretls_vers.o': can't open to read symbols: No such file or directory.
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_ciphersuites.a"
warning: Could not open OSO archive file (... more missing stuff here)

gdb seems to be partially working, e.g., I can set breakpoints, etc. but it seems to think all variables are integers, so it's totally useless for debugging anything with floats or doubles. I've seen lots of reports about this all over the place but not a single recommended solution anywhere or even an explanation of the issue (at least that's intelligible to me).

Any ideas? Thanks!!

**Comment by Wizmann** [comment]
Same problem here! Could any one can help us?

**Comment by fjarlq** [comment]
The warnings are a dup of issue #357. A harmless upstream issue, as far as I know.

I am having trouble reproducing the second problem you mention, about gdb thinking all variables are integers. Can you provide any details about that?

    $ cat t.c
    #include <stdio.h>
    int main() {
      int i = 4;
      float f = 12345.6789;
      double d = 98765.43210123;
      printf("%d %.2f %.2f\n", i, f, d);
      return 0;
    }
    $ gcc t.c -o t -g -Wall
    $ gdb t
    GNU gdb (GDB) 7.9.1
    Copyright (C) 2015 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-apple-darwin14.3.0".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from t...Reading symbols from /Users/mday/t.dSYM/Contents/Resources/DWARF/t...done.
    done.
    (gdb) b main
    Breakpoint 1 at 0x100000f26: file t.c, line 3.
    (gdb) r
    Starting program: /Users/mday/t
    warning: `/BinaryCache/coreTLS/coreTLS-35.30.2~2/Objects/coretls.build/coretls.build/Objects-normal/x86_64/system_coretls_vers.o': can't open to read symbols: No such file or directory.
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_ciphersuites.a"
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_handshake.a"
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_record.a"
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_stream_parser.a"

    Breakpoint 1, main () at t.c:3
    3	  int i = 4;
    (gdb) s
    4	  float f = 12345.6789;
    (gdb)
    5	  double d = 98765.43210123;
    (gdb)
    6	  printf("%d %.2f %.2f\n", i, f, d);
    (gdb) ptype i
    type = int
    (gdb) ptype f
    type = float
    (gdb) ptype d
    type = double
    (gdb) p i
    $1 = 4
    (gdb) p f
    $2 = 12345.6787
    (gdb) p d
    $3 = 98765.432101230006

**Comment by rbdavis** [comment]
GLOBAL variables, not local. You also need to split source into two files 
and compile separately as shown in the original post. (Or at least I think 
as shown, I can't check my original post right now.)

Roger

**Comment by fjarlq** [comment]
Ah, no, your original post did not show that. And I still can't reproduce the problem. Can you provide a small reproducible test case?

    $ cat globals.h
    extern int i;
    extern float f;
    extern double d;
    $ cat globals.c
    #include <stdio.h>
    #include "globals.h"
    int i = 4;
    float f = 12345.6789;
    double d = 98765.43210123;
    $ cat main.c
    #include <stdio.h>
    #include "globals.h"
    int main() {
      printf("%d %.2f %.2f\n", i, f, d);
      return 0;
    }
    $ gcc -Wall -g -c globals.c
    $ gcc -Wall -g -c main.c
    $ gcc -Wall -g -o main main.o globals.o
    $ ./main
    4 12345.68 98765.43
    $ gdb main
    GNU gdb (GDB) 7.9.1
    Copyright (C) 2015 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-apple-darwin14.3.0".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from main...done.
    (gdb) b main
    Breakpoint 1 at 0x100000f4b: file main.c, line 4.
    (gdb) r
    Starting program: /Users/mday/main
    warning: `/BinaryCache/coreTLS/coreTLS-35.30.2~2/Objects/coretls.build/coretls.build/Objects-normal/x86_64/system_coretls_vers.o': can't open to read symbols: No such file or directory.
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_ciphersuites.a"
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_handshake.a"
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_record.a"
    warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_stream_parser.a"
    
    Breakpoint 1, main () at main.c:4
    4	  printf("%d %.2f %.2f\n", i, f, d);
    (gdb) ptype i
    type = int
    (gdb) ptype f
    type = float
    (gdb) ptype d
    type = double
    (gdb) p i
    $1 = 4
    (gdb) p f
    $2 = 12345.6787
    (gdb) p d
    $3 = 98765.432101230006

**Comment by rbdavis** [comment]
My apologies, I posted a much more detailed example in another forum after my initial posting here, and  I have confused the two. I've been out of the office for a week, just got back today and disconfused myself. Also, I originally posted in this forum because a search turned up a similar bug here -- however, I am not actually using the homebrew gdb, so I abjectly apologize if this bug does not exist in homebrew. I would be surprised if it didn't, though, unless the homebrew gdb 7.9.1 is different from MacPorts gdb. Anyway, here's my test case:

% cat m0.c
#include \<stdio.h\>
float gf;
extern void func();
int main() {
        gf= 1.23;
        printf("gf: %4.2f\n", gf);
        func();
}

% cat m1.c
#include \<stdio.h\>
extern float gf;
void func() {
        float lf;
        lf= 4.56;
        printf("lf: %4.2f\n", lf);
}

Compile and link separately with

% cc -g -c m0.c -o m0.o
% cc -g -c m1.c -o m1.o
% cc -g -o m m0.o m1.o

When run under gdb, the type of the global float gf is unknown to gdb from within main():

% ggdb m
GNU gdb (GDB) 7.9.1
...
This GDB was configured as "x86_64-apple-darwin14.3.0".
...
Reading symbols from m...done.
(gdb) break main
Breakpoint 1 at 0x100000eee: file m0.c, line 5.
(gdb) break func
Breakpoint 2 at 0x100000f27: file m1.c, line 5.
(gdb) run
Starting program: /private/tmp/m
warning: `/BinaryCache/coreTLS/coreTLS-35.30.2~2/Objects/coretls.build/coretls.build/Objects-normal/x86_64/system_coretls_vers.o': can't open to read symbols: No such file or directory.
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_ciphersuites.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_handshake.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_record.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_stream_parser.a"
Breakpoint 1, main () at m0.c:5
5               gf= 1.23;
(gdb) s
6               printf("gf: %4.2f\n", gf);
(gdb) s
gf: 1.23
7               func();
(gdb) ptype gf
type = \<data variable, no debug info\>
(gdb) print gf
$1 = 1067282596

However, the type of local float lf within func() is known:

(gdb) continue
Continuing.
Breakpoint 2, func () at m1.c:5
5               lf= 4.56;
(gdb) s
6               printf("lf: %4.2f\n", lf);
(gdb) s
lf: 4.56
7       }
(gdb) ptype lf
type = float
(gdb) print lf
$2 = 4.55999994

The type of the global float gf is also unknown to gdb from within func():

(gdb) ptype gf
type = \<data variable, no debug info\>
(gdb) print gf
$3 = 1067282596

If instead you combine the two files m[01].c into the single file s.c with the contents

#include \<stdio.h\>
float gf;
int main() {
        void func();
        gf= 1.23;
        printf("gf: %4.2f\n", gf);
        func();
}

void func() {
        float lf;
        lf= 4.56;
        printf("lf: %4.2f\n", lf);
}

and compile with

% cc -o s -g s.c

then gdb works perfectly well, recognizing the type of gf and correctly printing its floating point value within either main() or func(). Naturally, the actual program I am having a problem with is much larger and really needs to be in multiple files, but I think this example shows the problem about as succinctly as possible. The problem is not limited to float variables -- a global int variable shows the same problem of unknown type.

Apologies again for not posting this code in full here earlier!

Roger

**Comment by cloudbow** [comment]
I am also facing the same issue.

**Comment by kedx** [comment]
Same issue bothering me, even updated to the newest version 7.10.
The messages are following when I try to 'run':
warning: `/BinaryCache/coreTLS/coreTLS-35.30.2~2/Objects/coretls.build/coretls.build/Objects-normal/x86_64/system_coretls_vers.o': can't open to read symbols: No such file or directory.
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_ciphersuites.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_handshake.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_record.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.30.2~2/Symbols/BuiltProducts/libcoretls_stream_parser.a"

**Comment by chaseWillden** [comment]
Same issue.

**Comment by benediktr** [comment]
Facing the same issue.

**Comment by XBOOS** [comment]
Same problems ! Any news?

**Comment by benediktr** [comment]
I gave up... using LLDB for now...

**Comment by XBOOS** [comment]
@benediktr Or you can return back to GDB7.7 which works fine. :)

**Comment by benediktr** [comment]
@XBOOS Sounds good. I will try that! Thanks for the hint!

**Comment by DevilDimon** [comment]
The issue still persists on 10.11 with gdb 7.10 for me.

**Comment by DomT4** [comment]
`gdb` got re-homed in the core, so let's move this issue there if necessary. As far as we can see on our side though this really needs kicking upstream for some discussion/thoughts. Thanks for the detailed examples to those who provided reproduction steps :heart:.

**Comment by franklinyu** [comment]
@XBOOS Do you have any idea how to install GDB 7.7 with Homebrew? Or I have to compile manually myself?

**Comment by XBOOS** [comment]
@franklinyu You could use this ruby file to install it.
https://gist.github.com/ymyzk/10ad2b74af9235eddb2c

**Comment by franklinyu** [comment]
@XBOOS Thank you so much! Saved my day. Google brings me here, so hopefully the next guy brought here by Google will see this formula too.

**Comment by jeasinema** [comment]
refer to  [some choices for gdb not working at OS X](http://stackoverflow.com/questions/27680712/homebrew-gdb-cant-open-core-file-on-yosemite-10-10)
