### ISSUE TITLE
OpenSSH_7.0p1, OpenSSL 1.0.2d [bug] authentification method password fails

### ISSUE THREAD

**Issue by 2mc** [Homebrew/homebrew-dupes#502]
After installing the current above versions of openSSH (and OpenSSL) via homebrew on OSX 10.10.4 and following this instructions of editing Apple's ssh.plist

    http://www.dctrwatson.com/2013/07/how-to-update-openssh-on-mac-os-x/ 

and a final reboot, the newly brewed sshd runs, login via rsa-keys works perfectly BUT password authentication fails.

I do get the prompt to enter my password, but it is simply not accepted.

If re-setting the ssh.plist to Apple's sshd binary and a restarting the service, my password gets again accepted at the prompt.

Note: no modifications have been made to /usr/local/etc/ssh/sshd_config, since password authentication is on by default and should work right away. Still I set this option explicitly for testing: 
     
      PasswordAuthentication yes 

But that didn't change anything.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
