### ISSUE TITLE
rsync: failed to install

### ISSUE THREAD

**Issue by z3a** [Homebrew/homebrew-dupes#506]
I found two errors while trying to install rsync in a Yosemite box.

1. The bottle is not present in the server
2. There is something wrong with the SSL handshake with the macports server.

```
==> Installing rsync from homebrew/homebrew-dupes
==> Downloading https://homebrew.bintray.com/bottles/rsync-3.1.1.yosemite.bottle

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "rsync"
Download failed: https://homebrew.bintray.com/bottles/rsync-3.1.1.yosemite.bottle.1.tar.gz

Warning: Bottle installation failed: building from source.
==> Downloading https://rsync.samba.org/ftp/rsync/rsync-3.1.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/rsync-3.1.1.tar.gz
==> Downloading https://trac.macports.org/export/127713/trunk/dports/net/rsync/f

curl: (35) Server aborted the SSL handshake
Error: Failed to download resource "rsync--patch"
Download failed: https://trac.macports.org/export/127713/trunk/dports/net/rsync/files/patch-fileflags.diff
```

**Comment by dunn** [comment]
You're trying to fetch an old bottle; `https://homebrew.bintray.com/bottles-dupes/rsync-3.1.1.yosemite.bottle.1.tar.gz` is what you should be getting.  Run `brew update` and try again.

MacPorts' Trac is currently down, so formulae with patches from them are currently failing.

**Comment by z3a** [comment]
Thanks @dunn for your answer. 'brew update' solved the issue.
