### ISSUE TITLE
brew install zlib  , fail , OSX EI Captain 10.11

### ISSUE THREAD

**Issue by 9723** [Homebrew/homebrew-dupes#523]
o  brew install zlib
==> Installing zlib from homebrew/homebrew-dupes
==> Downloading http://zlib.net/zlib-1.2.8.tar.gz
######################################################################## 100.0%
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/zlib/1.2.8
==> make install
1 error generated.
make: *** [infback.o] Error 1
make: *** [crc32.o] Error 1
1 error generated.
make: *** [deflate.o] Error 1

READ THIS: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-dupes/issues

**Comment by DomT4** [comment]
> READ THIS: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow the steps there.

**Comment by apjanke** [comment]
Closing due to lack of response.
