### ISSUE TITLE
Brew openssh not working

### ISSUE THREAD

**Issue by metron2** [Homebrew/homebrew-dupes#529]
When I try to install the latest openssh formulae I got a 404:

Download failed:
https://gist.githubusercontent.com/jacknagel/e4d68a979dca7f968bdb/raw/f07f00f9d5e4eafcba42cc0be44a47b6e1a8dd2a/sandbox.diff

**Comment by ShepherdHawkeye** [comment]
I'm seeing the same thing.

**Comment by DomT4** [comment]
Looking into it. The patch author has deleted the patch, it seems.

**Comment by ShepherdHawkeye** [comment]
If it helps, when I encountered the error I was running 
```
brew install openssh --with-brewed-openssl --with-ldns
```
I dropped the flags and it ran fine
```
brew install openssh
```

**Comment by DomT4** [comment]
That'll be because it's using the bottle I suspect, which comes pre-patched and consequently doesn't try to pull in the now dead link.
