### ISSUE TITLE
Provide GNU Texinfo 6.0

### ISSUE THREAD

**Issue by zmanji** [Homebrew/homebrew-dupes#540]
OSX ships with Texinfo but a very old version:

````
$ which info
/usr/bin/info

$ info --version
info (GNU texinfo) 4.8

Copyright (C) 2004 Free Software Foundation, Inc.
There is NO warranty.  You may redistribute this software
under the terms of the GNU General Public License.
For more information about these matters, see the files named COPYING.
````

Regular homebrew [ships](https://github.com/Homebrew/homebrew/blob/e3ef0bcf02e577082694622c893f5cffac83b2ca/Library/Formula/texinfo.rb) with texinfo 6.0 but it is keg only. Could it be placed in this repo so it can replace the binary provided by the system?

**Comment by dunn** [comment]
I don't have a strong preference either way so I'll defer to other maintainers, but FWIW you can `brew link --force texinfo` to link it to `/usr/local/bin`; then if your `$PATH` is set up right that'll be used instead of the system version.

**Comment by apjanke** [comment]
Yeah, I'd say go with the `brew link --force texinfo`; duplicating it under `dupes` doesn't seem like it would provide any extra functionality.

**Comment by DomT4** [comment]
Closing per the above replies.
