### ISSUE TITLE
brew install php70-mcrypt error  OS X El Capitan

### ISSUE THREAD

**Issue by schaffers** [Homebrew/homebrew-dupes#544]
==> Installing php70-mcrypt from homebrew/php
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:843:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:135:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:134:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:134:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:111:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:214:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:143:in `<main>'

Homebrew 0.9.5 (git revision bc02; last commit 2016-01-01)

**Comment by mistydemeo** [comment]
Can you post your `brew --config` and `brew doctor`?

**Comment by schaffers** [comment]
When I installed Xcode, errors was solved，Thanks
