### ISSUE TITLE
rsync crashes – malloc error: "pointer being freed was not allocated"

### ISSUE THREAD

**Issue by leonklingele** [Homebrew/homebrew-dupes#568]
Same issue as folks over at MacPorts experience with rsync's `-X` option:
https://trac.macports.org/ticket/50350

Version 3.1.2 is affected, previous version 3.1.1 (rev 6bb7624c0d1b361a71b316be6735c690a8a166df) not.

The problem appears when adding the 'X' option to copy extended attributes:
```
# Successful case
# -------------------
$ rsync -aP remoteserver:/sample-data .
receiving incremental file list
sample-data/
sample-data/foo.txt
              7 100%    6.84kB/s    0:00:00 (xfr#1, to-chk=2/4)
sample-data/hello.txt
             14 100%   13.67kB/s    0:00:00 (xfr#2, to-chk=1/4)
sample-data/mydate.txt
             29 100%   28.32kB/s    0:00:00 (xfr#3, to-chk=0/4)

# Now the error
# -------------------
$ rsync -aXP remoteserver:/sample-data .
receiving incremental file list
sample-data/
sample-data/foo.txt
              7 100%    6.84kB/s    0:00:00 (xfr#1, to-chk=2/4)
sample-data/hello.txt
             14 100%   13.67kB/s    0:00:00 (xfr#2, to-chk=1/4)
rsync(2689,0x7fff7bbac300) malloc: *** error for object 0x7fa300600070: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
rsync: connection unexpectedly closed (157 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [generator=3.1.2]
```

**Comment by dunn** [comment]
Do you know if this has been reported upstream? If not, could you do so? Thanks!

**Comment by ilovezfs** [comment]
The X option is pretty common so you're probably going to need to get a lot more specific for upstream to diagnose this.

**Comment by mgcrea** [comment]
I'm encountering issues as well with `3.1.2`, on of my rsync script that worked for over a year has stopped working, encountering sudden `inflate returned -3 (1809 bytes)` errors, workaround for now is to disable compression.

**Comment by ilovezfs** [comment]
@mgcrea Are both ends 3.1.2?

**Comment by mgcrea** [comment]
@ilovezfs, nop server is `3.1.0` (up-to-date Ubuntu 14.04.4)

```
$ rsync --version
rsync  version 3.1.0  protocol version 31
```

Reverting to rsync `3.1.1` on my mac does fix the issue.

**Comment by ilovezfs** [comment]
I'd be very curious whether the issue is reproducible if both sides are at 3.1.2, if you have the patience to test that configuration.

**Comment by mgcrea** [comment]
@ilovezfs what would be the easiest way to grab `3.1.2` on Ubuntu (ideally non-destructive)?

**Comment by ilovezfs** [comment]
@mgcrea Linuxbrew, of course. (What did you think I would say!) :)

**Comment by MikeMcQuaid** [comment]
Closing this upstream issue.
