### ISSUE TITLE
OpenSSH 7.1p2 connection fails with UsePrivilegeSeparation sandbox

### ISSUE THREAD

**Issue by bsolar17** [Homebrew/homebrew-dupes#577]
Trying to connect to the server configured with `UsePrivilegeSeparation sandbox` fails with this message in system.log:

> fatal: ssh_sandbox_child: sandbox_init: dlopen(/usr/lib/libsandbox.1.dylib, 261): image not found [preauth]

The connection with `UsePrivilegeSeparation yes` works.

**Comment by DomT4** [comment]
This should have been fixed by the new release, https://github.com/openssh/openssh-portable/commit/39f303b1f36d934d8410b05625f25c7bcb75db4d specifically.
