### ISSUE TITLE
Lapack... tailoring make

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/homebrew-dupes#579]
Not really an issue... Is there a way to accomplish the following with a brew install of Lapack?
```
cp INSTALL/make.inc.gfortran make.inc
```

and the in make.inc:
OPTS = -O2 -fPIC
NOOPT = -O0 -fPIC

```
cd SRC
make
```

**Comment by maxim-belkin** [comment]
Try: `buildpath.install "INSTALL/main.inc.gfortran", "make.inc"` [link](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md)

Now, what do you want to do with make.inc?

**Comment by jwhite007** [comment]
Thanks for the reply. This is in an effort to build ATLAS on which Scipy depends. I'm actually using Linuxbrew and not Homebrew, per se. I'm following the procedure outlined here... http://www.scipy.org/scipylib/building/linux.html under "Fedora Core 8, openSUSE 10.2, RHEL/Centos 5" Apparently the commands above create a lapack_<XXXX>.a file which is used for the ATLAS build.

**Comment by maxim-belkin** [comment]
So, the `scipy` version from `homebrew/python` tap does not have atlas?

**Comment by jwhite007** [comment]
I believe that I've tried to install Scipy via brew before. I'll try it again. I'd prefer to manage the Scipy install with pip; however.

**Comment by maxim-belkin** [comment]
So, what do you need to do with `make.inc`?

**Comment by jwhite007** [comment]
Apparently I have to edit it before the build

>Now, you must edit the make.inc file to ensure that the OPTS and NOOPT lines both contain the flag for compiling position-independent code on your platform (e.g. with gcc/gfortran it is -fPIC).

**Comment by maxim-belkin** [comment]
If these lines are in `make.inc`, then use `inreplace`, that is something like:
```ruby
inreplace "make.inc", /OPTS = .*/, "OPTS = -O2 -fPIC"
inreplace "make.inc", /NOOPT = .*/, "NOOPT = -O0 -fPIC"
```
See [examples](https://github.com/Homebrew/homebrew/commit/aad4dc23ece5869165b23f9637475503d2491db8).

The second part:
```ruby
cd "SRC" do
   system "make"
end
```

**Comment by jwhite007** [comment]
Thank you very much. I'll attempt this this afternoon.

**Comment by apjanke** [comment]
Is this still an issue?

**Comment by MikeMcQuaid** [comment]
> Not really an issue

Sounds like it is not.
