### ISSUE TITLE
OpenSSH 7.2p2 no longer installs slogin command

### ISSUE THREAD

**Issue by jj1bdx** [Homebrew/homebrew-dupes#585]
Unable to find `/usr/local/bin/slogin` symlink or `/usr/local/Cellar/openssh/7.2p2/bin/slogin` anymore.
Tested on OS X 10.11.4.

**Comment by DomT4** [comment]
Upstream killed it, but I'm sympathetic to re-adding it temporarily if there's demand to do so I guess.

**Comment by jj1bdx** [comment]
@DomT4 so the upstream maintainer now mandates use of `ssh` instead of `slogin`? Wow. Kinda surprised.

**Comment by DomT4** [comment]
Looks like it. It was yanked from a couple of the portable [spec](https://github.com/openssh/openssh-portable/commit/cff26f373c58457a32cb263e212cfff53fca987b)s as well. Debian's Changelog acknowledges the removal as well [here](http://metadata.ftp-master.debian.org/changelogs/main/o/openssh/openssh_7.2p2-2_changelog):

>   * Restore slogin symlinks for compatibility, although they were removed
    upstream.

**Comment by jj1bdx** [comment]
@DomT4 OK I understand your explanation. I don't mind if you ditch `slogin` altogether.

**Comment by DomT4** [comment]
I might put the symlink back for a release cycle for Homebrew, given upstream seem to have barely announced its removal and that might surprise others as it did you.

**Comment by jj1bdx** [comment]
@DomT4 I also think the upstream people should have more publicly announced the removal. I will follow your decision.

**Comment by DomT4** [comment]
Fixed by https://github.com/Homebrew/homebrew-dupes/commit/77cd263de1feec45b6874023d36e770c6b917379.

You'll need to `brew reinstall openssh` if you want the symlink back urgently, otherwise it'll re-appear the next time the version/revision is bumped. Thanks for the report!

**Comment by jj1bdx** [comment]
@domT4 Thx for reviewing and explaining this! :+1:
