### ISSUE TITLE
lsof download is failing

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew-dupes#591]
Building `lsof` from source is failing because the `url` and `mirror` aren't working. The main FTP URL (ftp://sunsite.ualberta.ca/pub/Mirror/lsof/lsof_4.88.tar.bz2) is timing out, and it looks like `lsof` has been removed from the mirror site (http://mirror.jaredwhiting.net/distfiles/lsof_4.88.tar.bz2).

Anybody know a current URL for `lsof`? The main project's URL, ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_4.89.tar.bz2, is working for me. Though its home page has some caveats about rejecting connections from hosts whose DNS records don't resolve satisfactorily; maybe that's why it's not being used already.

```
$ brew install -s lsof
==> Installing lsof from homebrew/dupes
==> Using the sandbox
==> Downloading ftp://sunsite.ualberta.ca/pub/Mirror/lsof/lsof_4.88.tar.bz2

curl: (28) Operation timed out after 5500 milliseconds with 0 out of 0 bytes received
Trying a mirror...
==> Downloading http://mirror.jaredwhiting.net/distfiles/lsof_4.88.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "lsof"
Download failed: http://mirror.jaredwhiting.net/distfiles/lsof_4.88.tar.bz2
```

**Comment by DomT4** [comment]
Resolved via https://github.com/Homebrew/homebrew-dupes/commit/034cf0f5aad367bc3d1c8f883b7fd8b41a2748d2 for now, using a mirror.
