### ISSUE TITLE
ncurses fails to build on RedHatEnterpriseServer 6.7 

### ISSUE THREAD

**Issue by nickjhathaway** [Homebrew/homebrew-dupes#622]
Following instructions here,  
https://github.com/Linuxbrew/linuxbrew/wiki/Standalone-Installation,  
I'm trying to install a standalone installation of linuxbrew on a RedHatEnterpriseServer 6.7 cluster. I'm running into an issue with homebrew/dupes/ncurses and the gist of the issue is here,  
https://gist.github.com/anonymous/3d5a6fa1fcb71d7d55f0afbabcc7b6b3#file-02-make-L2-L1440  
I wish i could be more specific but I'm having trouble figuring out what the error even is. What I'm running into is, 

```
...
...
/home/nh79w/.linuxbrew/bin/ginstall -c -m 644 ../lib/libncursesw_g.a /home/nh79w/.linuxbrew/Cellar/ncurses/6.0_1/lib/libncursesw_g.a
/home/nh79w/.linuxbrew/bin/ginstall: cannot stat '../lib/libncursesw_g.a': No such file or directory
...
...
```

And I'm not sure why that file isn't there for ginstall but it's the first error message i can find in the logs

I've ran brew update twice and haven't been able to find a similar issue already open.

**Comment by DomT4** [comment]
CC @sjackman.

**Comment by sjackman** [comment]
If you can install in `/home/linuxbrew/.linuxbrew` you can make use of precompiled binary bottles as a workaround.

Install errors like that are sometimes a race condition. Try:
```sh
HOMEBREW_MAKE_JOBS=1 brew install homebrew/dupes/ncurses
```

**Comment by nickjhathaway** [comment]
Excellent! 
```
HOMEBREW_MAKE_JOBS=1 brew install homebrew/dupes/ncurses
```
Worked and ncurses was able to install properly, thanks for the help!

**Comment by sjackman** [comment]
@DomT4 This should fix it:
```ruby
system "make"
ENV.deparallelize
system "make", "install"
```
With 32–256 threads I've noticed a number of race conditions that don't show up on desktop machines.

**Comment by DomT4** [comment]
@sjackman Mind filing a PR? Possibly worth nudging upstream as well. Things _should_ build in parallel, in an ideal world.

**Comment by sjackman** [comment]
Opened a PR at #630.
