### ISSUE TITLE
The ncurses bottle doesn't seem to exist

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-dupes#633]
If I try `brew install ncurses` it 404's, and if I try to paste the URL that it's trying to use into Safari, I get a "Requested Path Not Found".

That URL is: ` https://homebrew.bintray.com/bottles/ncurses-6.0_1.el_capitan.bottle.1.tar.gz`

**Comment by DomT4** [comment]
Not sure how you're hitting this via `fetch`?

```
==> Fetching ncurses from homebrew/dupes
==> Downloading https://homebrew.bintray.com/bottles-dupes/ncurses-6.0_1.el_capitan.bottle.1.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://homebrew.bintray.com/bottles-dupes/ncurses-6.0_1.el_capitan.bottle.1.tar.gz -C 0 -o /usr/local/var/homebrew/cache/ncurses-6.0_1.el_capitan.bottle.1.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2158k  100 2158k    0     0  1010k      0  0:00:02  0:00:02 --:--:-- 5089k
Downloaded to: /usr/local/var/homebrew/cache/ncurses-6.0_1.el_capitan.bottle.1.tar.gz
SHA256: ace4b172a3be12aa38e7bcedb4693ce560b2735c119c6ac549284e08b4fd3684
```

You're hitting the problem with Safari because the URL for the bottle changes per tap.

**Comment by chdiza** [comment]
Well, dang.  I bet the reason is that I didn't install it from the dupes tap.  I had a copy of the formula locally, and did `brew install ./ncurses.rb`. (And then conveniently forgot that fact when I made this report!) This used to successfully pour bottles, but perhaps the move to bintray changed this.

**Comment by DomT4** [comment]
I _suspect_ it broke when we introduced [this logic](https://github.com/Homebrew/brew/blob/9e7b8c61a99c4d4c69da36f95759e375b7a4e116/Library/Homebrew/software_spec.rb#L305-L311) combined with [this](https://github.com/Homebrew/brew/blob/44af0d80e88035419f2324005c77e2444d083e7d/Library/Homebrew/utils/bottles.rb#L60-L67).

That does seems like sane behaviour though, even if it tripped you in this case; I think it's reasonable that if you've a local copy we don't assume the bottle will automatically come from the same place as another identically named formula.

**Comment by ilovezfs** [comment]
That's an interesting corner case. I wonder if we could use the GitHubAPI to fix it?

**Comment by ilovezfs** [comment]
@MikeMcQuaid I suspect this is a "won't fix" though, yes?

**Comment by MikeMcQuaid** [comment]
Yeh, we don't support using formulae locally like that.

**Comment by chdiza** [comment]
> I think it's reasonable that if you've a local copy we don't assume the bottle will automatically come from the same place as another identically named formula.

I thought that the bottle SHA's basically contained all the relevant info about what is to be poured (i.e. were tantamount to a bottle URL), which is why it didn't seem to me that it should matter where the formula lives.  But probably my "thought" is not correct, even if it was once upon a time---and maybe it wasn't then, either. :)

**Comment by MikeMcQuaid** [comment]
The bottles themselves do but unfortunately it can't find the bottle purely from a formula. If you felt like it I'd be up for extrapolating the tap from the full path (or full URL).

**Comment by ilovezfs** [comment]
maybe we can use QR codes instead of sha256
