### ISSUE TITLE
"no acceptable grep"/"no acceptable sed" circular dependency

### ISSUE THREAD

**Issue by yaroslavvb** [Homebrew/homebrew-dupes#636]
I'm on El Capitan, and I can't seem to install GNU grep or sed because each one requires the other one to be upgraded first, any suggestion for a work-around?

IE, I get

```
brew install homebrew/dupes/grep --with-default-names
checking for a sed that does not truncate output... configure: error: no acceptable sed could be found in $PATH

```

on other hand
```
brew install gnu-sed --with-default-names
checking for grep that handles long lines and -e... configure: error: no acceptable grep could be found in /usr/local/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin:/usr/xpg4/bin

```

**Comment by ilovezfs** [comment]
superenv doesn't prefer homebrew dupes sed when installed with default names. The same is true for grep. So you can brew install --env=std and that may work around the problem. Or better yet, stop using --default-names and then make the gnubin directory first in your PATH afterwards.

**Comment by yaroslavvb** [comment]
Removing `--with-default-names` seems to fix things
