### ISSUE TITLE
srm no longer dupe in 10.12

### ISSUE THREAD

**Issue by tsujamin** [Homebrew/homebrew-dupes#638]
By the looks of things on 10.12 srm is no longer included in the base system/xcode-tools.

Does this mean the [srm recipe](https://github.com/Homebrew/homebrew-dupes/blob/master/srm.rb) should be moved out of dupes in the near future?

**Comment by DomT4** [comment]
It'd be interesting to know why Apple culled it in 10.12. Whether that's related to simply not having a use for the tool on the system any more, having replaced it with something else or the tool not being supported on the new filesystem Apple is working on.

But provisionally, once 10.12 is stable it could be moved into `homebrew/core` with a:
```ruby
keg_only :provided_pre_sierra
```
tag.

**Comment by tsujamin** [comment]
Yeah I'm curious too; I vaguely remember the man page still existing in a previous beta.

Sounds good, do we leave this issue open till then or close it for now?

**Comment by DomT4** [comment]
Yeah, was removed in the most recent beta. I suppose this is technically privileged information, but I presume Apple won't shoot me out of a cannon for sharing it given it's not particularly sensitive:

> This command-line tool has been removed because it is no longer useful on SSD/Flash-based systems.

Let's close here for now, but we can re-discuss once 10.12 is stable. Still a while to go yet.

**Comment by ilovezfs** [comment]
External hard drives don't actually exist, you see.

**Comment by DomT4** [comment]
Apple likes to follow a very aggressive deprecation schedule. I'm still barely getting used to not having a CD/DVD drive in my MacBook Pro 😄.

**Comment by ilovezfs** [comment]
>CD/DVD drive

Uncle Dominyk, what's a CD drive?

**Comment by DomT4** [comment]
Well ILZ, in the dark days before App Stores...

**Comment by DomT4** [comment]
That said, I do somewhat miss the reassurance of having a physical disk for things. I trust digital downloads less to not randomly vanish or become inaccessible one day. I still buy physical PS4 games for this reason! (I feel like we've derailed this thread by now 😄).
