### ISSUE TITLE
openssh 7.3p1: sshd won't take connections, @PREFIX@ in binary

### ISSUE THREAD

**Issue by philpennock** [Homebrew/homebrew-dupes#641]
With OpenSSH 7.3p1 installed from bottle, sshd will start and accept connections but kill all children; running `sudo /usr/local/sbin/sshd -D -d` we see:

```
debug1: Local version string SSH-2.0-OpenSSH_7.3
ssh_sandbox_child: sandbox_init: @PREFIX@/share/openssh/org.openssh.sshd.sb: profile not found [preauth]
```

That `@PREFIX@` comes from the patch `patch-sandbox-darwin.c-apple-sandbox-named-external.diff` and makes it through to the binary.

Making the `sshd` writable and running `hexedit` on it, to change the path to `/usr/local/etc/ssh/org.openssh.sshd.sb` without changing anything else, the bottled binary works and accepts connections without dying.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by DomT4** [comment]
Try `brew reinstall openssh`. I wasn't able to reproduce this locally, so maybe the bottle poured oddly for you locally or something.

**Comment by philpennock** [comment]
A Bottle is a _binary_ package. It can't be "poured oddly" to change the contents of the binary (without being a major security issue).

I do see that I neglected to provide platform information: 10.10.5 Yosemite; I did not review all bottles to determine if this flaw only affected some, as I (naively?) assumed that the same build process would be used on all platforms, so that what's a bug on one is a bug on all.

I will put a PR on my backlog burner of tasks, thanks.

**Comment by DomT4** [comment]
Sorry, I didn't realise you'd been maintaining Homebrew for quite some time now. Must have missed you in the team chat.

Homebrew performs [relocation on some strings](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg_relocate.rb) so that bottles are not always limited to the prefix they were built for. This has caused the occasional issue [before](https://github.com/Homebrew/legacy-homebrew/issues/41926). Forgetting temporarily that we use `@@HOMEBREW_PREFIX@@` as our marker rather than `@PREFIX@` I wondered if this was related.

As I said above, I cannot reproduce your issue. I look forwards to your PR.

**Comment by milli** [comment]
I have also had to hack the binary to make this work on Yosemite (10.10.5).  Any chance there's a fix forth coming?

**Comment by MikeMcQuaid** [comment]
> Any chance there's a fix forth coming?

There is not unless someone creates a PR.

**Comment by mattmartini** [comment]
I am seeing the same issue on Yosemite 10.10.5, sshd version OpenSSH_7.3, OpenSSL 1.0.2j  26 Sep 2016.  Any incoming connection causes:
debug1: Local version string SSH-2.0-OpenSSH_7.3
ssh_sandbox_child: sandbox_init: @PREFIX@/share/openssh/org.openssh.sshd.sb: profile not found [preauth]

**Comment by mattmartini** [comment]
I just submitted a pull request that fixes this issue.
https://github.com/Homebrew/homebrew-dupes/pull/665

**Comment by mattmartini** [comment]
Just upgraded to OpenSSH 7.4p1 and this issue is back!?  Figured you'd at least fix it in the new version even if you didn't want to fix the old version.

**Comment by techdad** [comment]
I have this issue.
Sierra 10.12.3 - homebrew  OpenSSH 7.4p1 compiled against LibreSSL:

ssh_sandbox_child: sandbox_init: @PREFIX@/share/openssh/org.openssh.sshd.sb: profile not found [preauth]
