### ISSUE TITLE
lapack implicitly depends on gcc5 (for bottles)

### ISSUE THREAD

**Issue by kevinushey** [Homebrew/homebrew-dupes#643]
With the El Capitan bottle of `lapack`, I see:

```
$ otool -L liblapack.3.dylib
liblapack.3.dylib:
        /usr/local/opt/lapack/lib/liblapack.3.dylib (compatibility version 3.0.0, current version 3.6.0)
        @rpath/libblas.3.dylib (compatibility version 3.0.0, current version 3.6.0)
        /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/lib/gcc/5/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/opt/gcc/lib/gcc/5/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Note that the directory paths point to a gcc-5 installation; however, the `gcc5` dependency is not declared in the `lapack` formula.

Does `lapack` need to explicitly depend on `gcc5`? Or, do the bottles need to be rebuilt against the current `gcc` formula and that dependency updated?

**Comment by ilovezfs** [comment]
that means it needs a revision bump.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-dupes/pull/644

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-dupes/pull/644.

**Comment by ilovezfs** [comment]
@kevinushey if you brew update and upgrade, you'll get 3.6.1, which is linked against gcc6 instead.

**Comment by kevinushey** [comment]
Awesome, can confirm everything looks good now. Thanks!

**Comment by ilovezfs** [comment]
you're welcome :)
