### ISSUE TITLE
how to install `gnu make' with infodoc?

### ISSUE THREAD

**Issue by introom** [Homebrew/homebrew-dupes#652]
I did a `brew install make`, but found no texinfo doc.

**Comment by dunn** [comment]
Sorry we missed this.  If there's a component not installed, we'd be happy to review a PR that installs it!  Take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md and let us know if you have questions.

**Comment by MikeMcQuaid** [comment]
Note any PR should be to homebrew/core now.
