### ISSUE TITLE
openssh: keychain support for macOS Sierra?

### ISSUE THREAD

**Issue by cebor** [Homebrew/homebrew-dupes#655]
Is there any way to get openssh working with macOS Sierra keychain?

On El Captian all was fine.

**Comment by chdiza** [comment]
AFAICT, no.  Sierra indeed broke the interaction between the *system* openssh's ssh-agent and the Keychain.

**Comment by DomT4** [comment]
@chdiza is correct. Homebrew _used_ to carry the keychain support patch optionally but it was a huge chunk of code nobody seemed to be security reviewing & upstream had no appetite to accept and maintain officially, so we removed it.

Don't quote me but people seem to be having some luck with sticking `AddKeysToAgent yes` in their `ssh_config`.

**Comment by chdiza** [comment]
> people seem to be having some luck

Do you mean luck in getting Sierra's "system" ssh-agent to interact properly with the macOS Keychain?

(I hope so, because that breakage is some top-flight BS.)

**Comment by DomT4** [comment]
Yeah, indeed, allegedly. That's what I've seen floating around. There's also this repo: https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain

**Comment by chdiza** [comment]
Thanks @DomT4.  The main problem I had was not that the system ssh-agent couldn't remember my password for my private key, it's that it remembers it despite it not being stored in the Keychain.  Nobody seems to know where it's being stored.  So I have no idea how to "clear" it if I wanted to.
