### ISSUE TITLE
srm is no longer in OS X, removed in 10.11

### ISSUE THREAD

**Issue by smileytechguy** [Homebrew/homebrew-dupes#662]
https://support.apple.com/en-us/HT205267
From the release notes, the secure empty trash is no longer there.
On my Sierra installation, srm is not there either and I would suggest moving this to homebrew-core and removing the keg-only flag.

**Comment by ilovezfs** [comment]
Apple may not be thrilled with our facilitating people ruining their SSDs …

**Comment by smileytechguy** [comment]
Print a message in caveats then.

**Comment by ilovezfs** [comment]
Boneyarding is probably a better move.

**Comment by smileytechguy** [comment]
Its you guys' decision, so I'll close this
