### ISSUE TITLE
tcl-tk package does not pass brew audit

### ISSUE THREAD

**Issue by kenh** [Homebrew/homebrew-dupes#670]
The tcl-tk package does not pass 'brew audit':

```
homebrew/dupes/tcl-tk:
  * Non-libraries were installed to "/usr/local/Cellar/tcl-tk/8.6.6/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/Cellar/tcl-tk/8.6.6/lib/Tk.icns
      /usr/local/Cellar/tcl-tk/8.6.6/lib/Tk.tiff
Error: 1 problem in 1 formula
```

I noticed this because I wanted to submit a fix for this formula when building the x11 version, but since the formula won't pass an audit with these problems my pull request doesn't go anywhere.
I did look at fixing this, but it seemed rather complicated and my Ruby skills aren't so great; help?

**Comment by ilovezfs** [comment]
The check was never originally intended to be fatal. Feel free to open the PR without fixing this.
