### ISSUE TITLE
TCL/TK SHA256 mismatch

### ISSUE THREAD

**Issue by Sorcim** [Homebrew/homebrew-dupes#671]
Hello, 

when I try to install TCL/TK package i have this error : 

`Error: SHA256 mismatch
Expected: 95c676130ce2fdb00e8a6f79c4fea9e79d071063783a61db9274647920d97a03
Actual: dfbe4388d161680dded6ea83ec3638afb056c76913e48d4b44165e2f5cc1a298
Archive: /Users/Johan/Library/Caches/Homebrew/tcl-tk--tcllib-1.17.tar.gz
To retry an incomplete download, remove the file above.`

i'm on OSX 10.12

**Comment by bfontaine** [comment]
You have an outdated formula. Please run `brew update` and try again.
