### ISSUE TITLE
rsync.rb with  --checksum-choice

### ISSUE THREAD

**Issue by gwarnes-mdsol** [Homebrew/homebrew-dupes#677]
Hi,

I would like to use the just introduced  '--checksum-choice=none'  option.  What is the cleanest way to update the rsync.rb formula to integrate this change?

Is it best to create an appropriate patch file, and add it to the formula?

-Greg

**Comment by dunn** [comment]
Sorry for the delay on this.

How likely is it that people will want this option?  Is there any downside to having it on by default?

**Comment by MikeMcQuaid** [comment]
Passing on this option, sorry. RSync has moved to homebrew/core for future reference.
