### ISSUE TITLE
rsync very outdated

### ISSUE THREAD

**Issue by lorddaedra** [Homebrew/homebrew-dupes#678]
Release date of 2.6.9 version is 6 November 2006 year, and current version is 3.1.2 (released 21 December 2015 so it look stable, almost year from release date).

Trouble is there is no simple way to install cli version of rsync on mac OS Sierra...

I can follow guides like that https://translate.google.com/translate?hl=ru&sl=ru&tl=en&u=http%3A%2F%2Fpavelurusov.com%2Frsync-in-mac-os-x%2F

and manually download source, apply patches, build, etc...

But it's not comfortably and easy for users... So, please, provide updated version of rsync...

``` These formulae duplicate software provided by OS X, though may provide more recent or bugfix versions. ```

So I feel, you can provide updated version.. Thank you.

**Comment by ilovezfs** [comment]
The 2.6.9 that Apple includes Apple-specific customizations and patches. It is not a stock 2.6.9 build, and this rsync in homebrew/dupes is an unneeded replacement for the vast majority of users.
