### ISSUE TITLE
tcl-tk: SHA256 mismatch

### ISSUE THREAD

**Issue by stephsamson** [Homebrew/homebrew-dupes#690]
When doing `brew install tcl-tk`, I get the following error:

```
Error: SHA256 mismatch
Expected: 95c676130ce2fdb00e8a6f79c4fea9e79d071063783a61db9274647920d97a03
Actual: dfbe4388d161680dded6ea83ec3638afb056c76913e48d4b44165e2f5cc1a298
```

**Comment by dunn** [comment]
I'm getting the expected hash; can you still reproduce this?

**Comment by stephsamson** [comment]
@dunn Yes, I can, with the exact same actual hash as above. I should also mention that I'm using macOS Sierra.

**Comment by ilovezfs** [comment]
That's the checksum on tcllib-1.17 not 1.18, which means your brew is very outdated and this issue is moot.

You may have been a victim of https://twitter.com/MacHomebrew/status/763686348041641984 so I recommend you follow the instructions there.

**Comment by stephsamson** [comment]
Thanks @ilovezfs ! That did the trick :)

**Comment by ilovezfs** [comment]
@stephsamson Nice! Glad to hear it.
