### ISSUE TITLE
openssh 7.4p1 sshd won't take connections, @PREFIX@ in binary - unresolved from #641

### ISSUE THREAD

**Issue by mattmartini** [Homebrew/homebrew-dupes#697]
The problem in issue #641 "openssh 7.3p1: sshd won't take connections, @PREFIX@ in binary" is back and still not resolved.  I had provided a PR for #641 but it was not accepted (it was an ugly patch).

However, @PREFIX@ macro is not getting properly expanded and is winding up in the binary.  This causes ALL connections to fail.

The fix is pretty simple:

```
-	if (sandbox_init("@PREFIX@/share/openssh/org.openssh.sshd.sb",
+	if (sandbox_init("/System/Library/Sandbox/Profiles/org.openssh.sshd.sb",
```

Please incorporate this fix.

My configuration is Yosemite, Mac OS 10.10.5

**Comment by mattmartini** [comment]
A pull request was created for this issue at:

https://github.com/Homebrew/formula-patches/pull/98

**Comment by mattmartini** [comment]
I submitted a working patch (for Yosemite) (see prev comment) but there is an issue because the patch needs to be different for Sierra (text in patch needs to be "com.openssh.sshd.sb" instead of "org.openssh.sshd.sb") and I am not sure how to make the patch conditional on the OS version.

**Comment by MikeMcQuaid** [comment]
Note I don't think we should be accepting pull requests to OpenSSH until they are submitted and merged upstream. The potential to introduce security regressions is too high.

**Comment by mattmartini** [comment]
This is not a change to OpenSSH but to the brew specific patch that allows Macs to use the package.  However, this brew patch is broken (the sshd binary does not allow connections) because the path specified has "@PREFIX" literally in it.  This macro is not expanded (to the correct path of /System/Library/Sandbox/Profiles/) and the resulting binary is useless.    

I would argue that by leaving this broken, users are forced to use on older (read less secure) version of OpenSSH or forgo the use of ssh which is not a viable option.

**Comment by techdad** [comment]
I have this issue.
Sierra 10.12.3 - homebrew OpenSSH 7.4p1 compiled against LibreSSL:

ssh_sandbox_child: sandbox_init: @PREFIX@/share/openssh/org.openssh.sshd.sb: profile not found [preauth]

Interesting that it's "org.openssh.sshd.sb" and not "com.openssh.sshd.sb" in my case. I'd also very much like this to work. In fact my ultimate wish list would be to have sshd under "brew services list".

I'm happy to help test any plist or other patches before final commits.

**Comment by techdad** [comment]
Also tried with bottled openssh 7.4p1 👍 

debug1: sshd version OpenSSH_7.4, OpenSSL 1.0.2k  26 Jan 2017

ssh_sandbox_child: sandbox_init: @PREFIX@/share/openssh/org.openssh.sshd.sb: profile not found [preauth]
debug1: do_cleanup [preauth]
debug1: monitor_read_log: child log fd closed
debug1: do_cleanup
debug1: Killing privsep child 13306

**Comment by MikeMcQuaid** [comment]
Will consider accepting this patch (in homebrew/core where this formula will be by then) when it was submitted upstream.
