### ISSUE TITLE
openssh doesn't support GSSAPITrustDNS and GSSAPIKeyExchange

### ISSUE THREAD

**Issue by RobberPhex** [Homebrew/homebrew-dupes#712]
When I use `ssh` (in package `openssh`), and configured `GSSAPITrustDNS` and `GSSAPIKeyExchange`, ssh reports:

````
Bad configuration option: gssapitrustdns
Bad configuration option: gssapikeyexchange
terminating, 2 bad configuration options
````

But in Fedora <http://pkgs.fedoraproject.org/cgit/rpms/openssh.git/tree/?h=f25>, openssh support it. Is there some special patches?

**Comment by garfielde** [comment]
Its this patch that enables those options: http://pkgs.fedoraproject.org/cgit/rpms/openssh.git/tree/openssh-7.2p1-gsskex.patch?h=f25

I manually patched the trustDNS option on my system.

**Comment by MikeMcQuaid** [comment]
Closing as we don't want to apply custom patches to OpenSSH, sorry!

**Comment by garfielde** [comment]
Neither does Apple ;)
