### ISSUE TITLE
openssh error on macOS 10.12.0

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-dupes#716]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:
```
ssh -T git@github.com
dyld: lazy symbol binding failed: Symbol not found: _timingsafe_bcmp
  Referenced from: /usr/local/bin/ssh
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _timingsafe_bcmp
  Referenced from: /usr/local/bin/ssh
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```
Tried both: bottle and building from source.

**Comment by sds** [comment]
Wanted to confirm that I experienced this same problem on 10.12.0 and fixed it by upgrading to 10.12.3.

**Comment by ilovezfs** [comment]
Right, that symbol wasn't in 10.12.0, so I'm closing this since we only support the latest point release of each macOS version. You can fix it by building from source or by upgrading to 10.12.3.

**Comment by 2zz2** [comment]
how to update

**Comment by yurikoles** [comment]
@2zz2 Apple icon on top left corner of the screen -> AppStore -> Updates tab

**Comment by 2zz2** [comment]
oh,my god~updating system~thank you so much
