### ISSUE TITLE
tcl-tk install fails due to sourceforge mirror failure

### ISSUE THREAD

**Issue by aholtventuretech** [Homebrew/homebrew-dupes#730]
Trying to install a homebrew tap that depends on homebrew/dupes/tcl-tk, and it is failing.

When attempting to download homebrew/dupes/tcl-tk, it looks like the Sourceforge mirror is failing, and causing the installation to completely fail.

These are the log lines I see when it fails:
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.6/tcl8.6.6-src.tar.gz
==> Downloading https://downloads.sourceforge.net/mirrorproblem?failedmirror=svwh.dl.sourceforge.net

Then I get a SHA256 mismatch error.
You will notice that the second url it tries downloading from is definitely not a valid download url.

**Comment by ilovezfs** [comment]
Interesting ... I just hit a sourceforge mirror fail too:
```
==> Installing homebrew/science/graph-tool dependency: boost-python
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2
==> Downloading from http://downloads.sourceforge.net/mirrorproblem?failedmirror=svwh.dl.sourceforge.net
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: beae2529f759f6b3bf3f4969a19c2e9d6f0c503edcb2de4a61d1428519fcb3b0
Actual: 0fa26e565c169723e288b52de47a0cb6d838450b26d404726330adde3147eb4a
Archive: /Users/joe/Library/Caches/Homebrew/boost-python-1.63.0.tar.bz2
To retry an incomplete download, remove the file above.
```

**Comment by ilovezfs** [comment]
@aholtventuretech mind just trying again? Seems to be downloading now for me
```
==> Downloading from https://svwh.dl.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2
##                                                                         3.7%
```

**Comment by aholtventuretech** [comment]
@ilovezfs  looks like the download is working now.

Still think there should be some sort of contingency for this.  There are valid mirrors, otherwise I would not have been able to download tcl directly from sourceforge.

It looks like there may be an issue with handling a failed mirror?

**Comment by ilovezfs** [comment]
I don't think there's much we can do here. The url https://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2 please-use-some-good-mirror url for sourceforge. If that ends up resolving to garbage during the download, it's a little late for us to be attempting to jump in and second guess the redirect.

**Comment by aholtventuretech** [comment]
good point.  sounds like at that point, the ball is squarely in SourceForge's ballpark.

Thanks!  I'll close this now.

**Comment by aholtventuretech** [comment]
The mirror was down again earlier, and was wrecking havoc with my automated install script, which could not get past the point of installing tcl-tk.

I'm reopening this issue to propose a solution to this:

Change the download location from sourceforge, to the alternative download location specified on the tcl-tk site:  ftp://ftp.tcl.tk/pub/tcl/tcl8_6/tcl8.6.6-src.tar.gz

**Comment by fxcoudert** [comment]
Mirrors now added
