### ISSUE TITLE
Sha256 mismatch error for tcllib 1.18

### ISSUE THREAD

**Issue by kluophysics** [Homebrew/homebrew-dupes#740]
[https://github.com/Homebrew/homebrew-dupes/issues/657](it is closed by the same problem persists)

Can anyone help take a look at this? Thanks!

==> ./configure --prefix=/usr/local/Cellar/tcl-tk/8.6.6 --mandir=/usr/local/Cellar/tcl-tk/8.6.6/s
==> make TK_LIBRARY=/usr/local/Cellar/tcl-tk/8.6.6/lib
==> make install
==> make install-private-headers
==> Downloading https://github.com/tcltk/tcllib/archive/tcllib_1_18.tar.gz
==> Downloading from https://codeload.github.com/tcltk/tcllib/tar.gz/tcllib_1_18
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 6a87881f545afb69c1130f60984b5d35cc22f1593b0835b982871c188fde3de8
Actual: 9988b4385403c2aac78743fd3fce2d22e82686a56e6ca25942cb83c7d9e641db

**Comment by JCount** [comment]
This should hopefully be fixed by https://github.com/Homebrew/homebrew-dupes/pull/738
